// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:

/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfPhlw1iLeJykrLg4yMsRuDc4DFASswxk',
    appId: '1:115204385017:web:8e425995fb51f88a71da28',
    messagingSenderId: '115204385017',
    projectId: 'book-managment-4516c',
    authDomain: 'book-managment-4516c.firebaseapp.com',
    storageBucket: 'book-managment-4516c.firebasestorage.app',
    measurementId: 'G-EB1N5R2LHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAotPUTkwFHdjUUNiDZVEzBohj4QZtcht0',
    appId: '1:115204385017:android:5e74ab6f29e7812b71da28',
    messagingSenderId: '115204385017',
    projectId: 'book-managment-4516c',
    storageBucket: 'book-managment-4516c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWoD6ouMrvgV-3Spn7L_cf5Mb9zsaC4A4',
    appId: '1:115204385017:ios:72a20dc4d09590a171da28',
    messagingSenderId: '115204385017',
    projectId: 'book-managment-4516c',
    storageBucket: 'book-managment-4516c.firebasestorage.app',
    iosBundleId: 'com.example.bookManagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWoD6ouMrvgV-3Spn7L_cf5Mb9zsaC4A4',
    appId: '1:115204385017:ios:72a20dc4d09590a171da28',
    messagingSenderId: '115204385017',
    projectId: 'book-managment-4516c',
    storageBucket: 'book-managment-4516c.firebasestorage.app',
    iosBundleId: 'com.example.bookManagment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfPhlw1iLeJykrLg4yMsRuDc4DFASswxk',
    appId: '1:115204385017:web:53137532b429dd2971da28',
    messagingSenderId: '115204385017',
    projectId: 'book-managment-4516c',
    authDomain: 'book-managment-4516c.firebaseapp.com',
    storageBucket: 'book-managment-4516c.firebasestorage.app',
    measurementId: 'G-VBQLLTEDRW',
  );
}
